
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Katso Bosele
 */
public class pizzaorder extends javax.swing.JFrame {

    /**
     * Creates new form pizzaorder
     */
    public pizzaorder() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        usernametxt = new javax.swing.JTextField();
        surnametxt = new javax.swing.JTextField();
        passwordtxt = new javax.swing.JTextField();
        gendercomb = new javax.swing.JComboBox<>();
        capturebtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        loginusernametxt = new javax.swing.JTextField();
        loginpasswordtxt = new javax.swing.JTextField();
        loginbtn = new javax.swing.JButton();
        cheesecb = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        avocadocb = new javax.swing.JCheckBox();
        baconcb = new javax.swing.JCheckBox();
        mushroomcb = new javax.swing.JCheckBox();
        toppricetxt = new javax.swing.JTextField();
        pepperonicb = new javax.swing.JCheckBox();
        thincrustrb = new javax.swing.JRadioButton();
        deeppanrb = new javax.swing.JRadioButton();
        glutonfreerb = new javax.swing.JRadioButton();
        basepricetxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        calculatebtn = new javax.swing.JButton();
        amounttxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("username:");

        jLabel2.setText("surname:");

        jLabel3.setText("password:");

        jLabel4.setText("gender:");

        gendercomb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "please choose gender", "Male", "Female" }));

        capturebtn.setText("capture");
        capturebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capturebtnActionPerformed(evt);
            }
        });

        jLabel5.setText("username:");

        jLabel6.setText("password:");

        loginbtn.setText("Login");
        loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtnActionPerformed(evt);
            }
        });

        buttonGroup1.add(cheesecb);
        cheesecb.setText("Cheese");
        cheesecb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cheesecbActionPerformed(evt);
            }
        });

        jLabel7.setText("Select Toppings");

        buttonGroup1.add(avocadocb);
        avocadocb.setText("Avocado");
        avocadocb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avocadocbActionPerformed(evt);
            }
        });

        buttonGroup1.add(baconcb);
        baconcb.setText("Bacon");
        baconcb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baconcbActionPerformed(evt);
            }
        });

        buttonGroup1.add(mushroomcb);
        mushroomcb.setText("Mushroom");
        mushroomcb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mushroomcbActionPerformed(evt);
            }
        });

        buttonGroup1.add(pepperonicb);
        pepperonicb.setText("pepperoni");
        pepperonicb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pepperonicbActionPerformed(evt);
            }
        });

        buttonGroup2.add(thincrustrb);
        thincrustrb.setText("Thin Crust");
        thincrustrb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thincrustrbActionPerformed(evt);
            }
        });

        buttonGroup2.add(deeppanrb);
        deeppanrb.setText("Deep Pan");
        deeppanrb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deeppanrbActionPerformed(evt);
            }
        });

        buttonGroup2.add(glutonfreerb);
        glutonfreerb.setText("Gluton-Free");
        glutonfreerb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                glutonfreerbActionPerformed(evt);
            }
        });

        basepricetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basepricetxtActionPerformed(evt);
            }
        });

        jLabel8.setText("choose crust type:");

        calculatebtn.setText("Calculate");
        calculatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculatebtnActionPerformed(evt);
            }
        });

        jLabel9.setText("Amount:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calculatebtn)
                    .addComponent(pepperonicb)
                    .addComponent(jLabel7)
                    .addComponent(capturebtn)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(surnametxt)
                                    .addComponent(usernametxt)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(gendercomb, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passwordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(avocadocb)
                                    .addComponent(cheesecb))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(baconcb)
                                    .addComponent(mushroomcb))
                                .addGap(28, 28, 28))
                            .addComponent(toppricetxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(loginpasswordtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                    .addComponent(loginusernametxt)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(loginbtn)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jLabel9)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(basepricetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(deeppanrb, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(glutonfreerb, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(thincrustrb, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(amounttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(usernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(loginusernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(surnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(loginpasswordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(passwordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginbtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(gendercomb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(capturebtn)
                    .addComponent(amounttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cheesecb)
                    .addComponent(baconcb)
                    .addComponent(thincrustrb))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(avocadocb)
                    .addComponent(mushroomcb)
                    .addComponent(deeppanrb))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pepperonicb)
                    .addComponent(glutonfreerb))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(basepricetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toppricetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(calculatebtn)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void capturebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capturebtnActionPerformed
        // TODO add your handling code here:
        String usrname = usernametxt.getText();
        String srname = surnametxt.getText();
        String passwrd = passwordtxt.getText();
        String gendr = gendercomb.getSelectedItem().toString();
        
        
        captureUser(usrname,srname,passwrd,gendr);
        
    }//GEN-LAST:event_capturebtnActionPerformed

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed
        // TODO add your handling code here:
        String loginusername = loginusernametxt.getText();
        String loginpassword = loginpasswordtxt.getText();
        
        loginUser(loginusername,loginpassword);
        
    }//GEN-LAST:event_loginbtnActionPerformed

    private void cheesecbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cheesecbActionPerformed
        // TODO add your handling code here:
        toppingprice = 15;
        boolean selected = cheesecb.isSelected();
        
        topping(toppingprice,selected);
    }//GEN-LAST:event_cheesecbActionPerformed

    private void baconcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baconcbActionPerformed
        // TODO add your handling code here:
          toppingprice = 25;
        boolean selected = baconcb.isSelected();
        
        topping(toppingprice,selected);
        
    }//GEN-LAST:event_baconcbActionPerformed

    private void avocadocbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avocadocbActionPerformed
        // TODO add your handling code here:
          toppingprice = 30;
        boolean selected = avocadocb.isSelected();
        
        topping(toppingprice,selected);
    }//GEN-LAST:event_avocadocbActionPerformed

    private void mushroomcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mushroomcbActionPerformed
        // TODO add your handling code here:
          toppingprice = 10;
        boolean selected = mushroomcb.isSelected();
        
        topping(toppingprice,selected);
    }//GEN-LAST:event_mushroomcbActionPerformed

    private void pepperonicbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pepperonicbActionPerformed
        // TODO add your handling code here:
           toppingprice = 20;
        boolean selected = pepperonicb.isSelected();
        
        topping(toppingprice,selected);
    }//GEN-LAST:event_pepperonicbActionPerformed

    private void basepricetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basepricetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_basepricetxtActionPerformed

    private void thincrustrbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thincrustrbActionPerformed
        // TODO add your handling code here:
           baseprice = 10;
        boolean chosen = thincrustrb.isSelected();
        
        baseprice(baseprice,chosen);
    }//GEN-LAST:event_thincrustrbActionPerformed

    private void deeppanrbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deeppanrbActionPerformed
        // TODO add your handling code here:
          baseprice = 15;
        boolean chosen = deeppanrb.isSelected();
        
        baseprice(baseprice,chosen);
    }//GEN-LAST:event_deeppanrbActionPerformed

    private void glutonfreerbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_glutonfreerbActionPerformed
        // TODO add your handling code here:
          baseprice = 20;
        boolean chosen = glutonfreerb.isSelected();
        
        baseprice(baseprice,chosen);
    }//GEN-LAST:event_glutonfreerbActionPerformed

    private void calculatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculatebtnActionPerformed
        // TODO add your handling code here:
        int payment = Integer.parseInt( amounttxt.getText());
        
        
        totalexpenses = baseprice + toppingprice;
        totalchange = payment - totalexpenses;
        
        JOptionPane.showMessageDialog(rootPane, "your payement of:R "+ payment + "And you total expenses are: R" +totalexpenses + "therefore your total change is: R" + totalchange);
        
        
    }//GEN-LAST:event_calculatebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    
        String username[] = new String[1];
        String password[] = new String[1];
        String surname[] = new String[1];
        String gender[] = new String[1];
        
        int toppingprice = 0;
        int baseprice = 0;
        int totalexpenses = 0;
        int totalchange = 0;
        double amount = 0;
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pizzaorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pizzaorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pizzaorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pizzaorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pizzaorder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amounttxt;
    private javax.swing.JCheckBox avocadocb;
    private javax.swing.JCheckBox baconcb;
    private javax.swing.JTextField basepricetxt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton calculatebtn;
    private javax.swing.JButton capturebtn;
    private javax.swing.JCheckBox cheesecb;
    private javax.swing.JRadioButton deeppanrb;
    private javax.swing.JComboBox<String> gendercomb;
    private javax.swing.JRadioButton glutonfreerb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton loginbtn;
    private javax.swing.JTextField loginpasswordtxt;
    private javax.swing.JTextField loginusernametxt;
    private javax.swing.JCheckBox mushroomcb;
    private javax.swing.JTextField passwordtxt;
    private javax.swing.JCheckBox pepperonicb;
    private javax.swing.JTextField surnametxt;
    private javax.swing.JRadioButton thincrustrb;
    private javax.swing.JTextField toppricetxt;
    private javax.swing.JTextField usernametxt;
    // End of variables declaration//GEN-END:variables

    private void captureUser(String usrname, String srname, String passwrd, String gendr) {
     
    if(usrname.isEmpty()||srname.isEmpty()||passwrd.isEmpty()||gendr.equals("please choose gender")){
        JOptionPane.showMessageDialog(rootPane, "Please enter all your details");
    }else
        username[0] = usrname;
        surname[0] = srname;
        password[0] = passwrd;
        gender[0] = gendr;
        
        JOptionPane.showMessageDialog(rootPane, "Successfuly captured");
    
    }

    private void loginUser(String loginusername, String loginpassword) {
       
        if(loginusername.isEmpty()||loginpassword.isEmpty()){
            
            JOptionPane.showMessageDialog(rootPane, "Please enter all login details");
            
        }else if(loginusername.equals(username[0]) && loginpassword.equals(password[0])){
            JOptionPane.showMessageDialog(rootPane, "Successful login");
        }else 
            JOptionPane.showMessageDialog(rootPane, "incorrect login");
    
    
    }

    private void topping(int toppingprice, boolean selected) {
      
        if(selected == true){
            toppricetxt.setText(String.valueOf(toppingprice));
        }
    
    }

    private void baseprice(int baseprice, boolean chosen) {
       
        if(chosen ==  true){
            basepricetxt.setText(String.valueOf(baseprice));
        }
    
    }
}
